
#include "Factory.hpp"

using namespace AOC::Challenges;

#define REGISTER_CHALLENGE(CHALLENGE_TYPE_NAME) \
    Factory::Register(CHALLENGE_TYPE_NAME::GetID(), [](std::vector<std::string>&& input) { return std::make_unique<CHALLENGE_TYPE_NAME>(std::move(input)); });

#include "Challenges/AutoGenerated/ChallengeIncludes.inl"
#include "Challenges/AutoGenerated/ChallengeRegistration.inl"

void Factory::RegisterAllChallenges()
{
#ifdef AUTO_GENERATED_CHALLENGE_REGISTRATION
    AUTO_GENERATED_CHALLENGE_REGISTRATION
#undef AUTO_GENERATED_CHALLENGE_REGISTRATION
#endif
}

#undef REGISTER_CHALLENGE
